#!/bin/sh

DAEMON_PATH="/usr/bin"
DAEMON_NAME="aesdsocket"
DAEMON_OPTS="-d"

PIDFILE="/var/run/$DAEMON_NAME.pid"

case "$1" in
	start)
		echo "Starting $DAEMON_NAME"
		start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- $DAEMON_OPTS
		echo "Started $DAEMON_NAME succesfully" 
		;;
	stop)
		echo "Stopping $DAEMON_NAME"
		start-stop-daemon --stop --pidfile $PIDFILE
		echo "Stopped $DAEMON_NAME successfully"
		;;
	*)
		echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
