#!/bin/sh

DAEMON_PATH="/usr/bin"
DAEMON_NAME="aesdsocket"
DAEMON_OPTS="-d"

PIDFILE="/var/run/$DAEMON_NAME.pid"

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting $DAEMON_NAME"
		start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- $DAEMON_OPTS
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $DAEMON_NAME"
		start-stop-daemon --stop --pidfile $PIDFILE
		log_end_msg $?
		;;
	restart)
		log_daemon_msg "Restarting $DAEMON_NAME"
		start-stop-daemon --stop --pidfile $PIDFILE
		sleep 1
		start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- $DAEMON_OPTS
		log_end_msg $?
		;;
	status)
		status_of_proc -p $PIDFILE $DAEMON_NAME && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
